import { FloorPlanData, Room, Door, Window, Furniture } from '../types';

export const mockStudioApartment: FloorPlanData = {
  rooms: [
    {
      id: 'r1',
      name: 'Sala & Quarto Integrados',
      x: 1.0,
      y: 1.0,
      width: 5.0,
      height: 5.5,
      color: '#e2f0fb',
      floorMaterial: 'wood',
      wallColor: '#f8fafc',
    },
    {
      id: 'r2',
      name: 'Cozinha Americana',
      x: 6.0,
      y: 1.0,
      width: 3.5,
      height: 2.5,
      color: '#fef3c7',
      floorMaterial: 'tile',
      wallColor: '#fffbeb',
    },
    {
      id: 'r3',
      name: 'Banheiro Executivo',
      x: 6.0,
      y: 3.5,
      width: 3.5,
      height: 3.0,
      color: '#ccfbf1',
      floorMaterial: 'marble',
      wallColor: '#f0fdfa',
    },
  ],
  doors: [
    {
      id: 'd1',
      roomId: 'r1',
      wall: 'bottom',
      offset: 1.2,
      width: 0.9,
      isOpen: true,
    },
    {
      id: 'd2',
      roomId: 'r2',
      wall: 'bottom',
      offset: 0.5,
      width: 0.8,
      isOpen: false,
    },
    {
      id: 'd3',
      roomId: 'r3',
      wall: 'left',
      offset: 1.0,
      width: 0.8,
      isOpen: true,
    },
  ],
  windows: [
    {
      id: 'w1',
      roomId: 'r1',
      wall: 'top',
      offset: 1.5,
      width: 1.6,
    },
    {
      id: 'w2',
      roomId: 'r2',
      wall: 'right',
      offset: 0.8,
      width: 1.2,
    },
    {
      id: 'w3',
      roomId: 'r3',
      wall: 'right',
      offset: 1.5,
      width: 0.6,
    },
  ],
  furniture: [
    {
      id: 'f1',
      name: 'Sofá de 3 Lugares',
      type: 'couch',
      roomId: 'r1',
      x: 0.5,
      y: 0.5,
      width: 2.0,
      height: 0.9,
      rotation: 0,
    },
    {
      id: 'f2',
      name: 'Cama Casal Queen',
      type: 'bed',
      roomId: 'r1',
      x: 2.8,
      y: 2.8,
      width: 1.8,
      height: 2.0,
      rotation: 90,
    },
    {
      id: 'f3',
      name: 'Televisor e Rack',
      type: 'tv',
      roomId: 'r1',
      x: 0.5,
      y: 3.0,
      width: 1.4,
      height: 0.4,
      rotation: 270,
    },
    {
      id: 'f4',
      name: 'Vaso de Planta Lira',
      type: 'plant',
      roomId: 'r1',
      x: 4.0,
      y: 0.5,
      width: 0.6,
      height: 0.6,
      rotation: 0,
    },
    {
      id: 'f5',
      name: 'Geladeira Duplex',
      type: 'fridge',
      roomId: 'r2',
      x: 0.5,
      y: 0.4,
      width: 0.8,
      height: 0.8,
      rotation: 180,
    },
    {
      id: 'f6',
      name: 'Fogão 4 Bocas',
      type: 'stove',
      roomId: 'r2',
      x: 2.0,
      y: 0.4,
      width: 0.7,
      height: 0.6,
      rotation: 180,
    },
    {
      id: 'f7',
      name: 'Bancada com Pia',
      type: 'cabinet',
      roomId: 'r2',
      x: 1.0,
      y: 1.5,
      width: 1.8,
      height: 0.7,
      rotation: 0,
    },
    {
      id: 'f8',
      name: 'Box de Chuveiro Vidro',
      type: 'shower',
      roomId: 'r3',
      x: 2.2,
      y: 0.5,
      width: 1.0,
      height: 1.0,
      rotation: 0,
    },
    {
      id: 'f9',
      name: 'Vaso Sanitário',
      type: 'toilet',
      roomId: 'r3',
      x: 0.5,
      y: 2.0,
      width: 0.5,
      height: 0.7,
      rotation: 90,
    },
    {
      id: 'f10',
      name: 'Lavatório e Espelho',
      type: 'sink',
      roomId: 'r3',
      x: 2.0,
      y: 2.0,
      width: 0.8,
      height: 0.6,
      rotation: 270,
    },
  ],
  estimatedCost: {
    structural: 48500,
    flooring: 12400,
    installations: 18000,
    total: 78900,
    materialsBreakdown: [
      { item: 'Paredes em Alvenaria Estrutural', quantity: '120 m²', cost: 24000 },
      { item: 'Piso Laminado de Madeira Nobre', quantity: '27.5 m²', cost: 6875 },
      { item: 'Porcelanato Antiderrapante', quantity: '10.5 m²', cost: 3150 },
      { item: 'Revestimento de Mármore', quantity: '10.5 m²', cost: 5800 },
      { item: 'Esquadrias de Alumínio e Janelas', quantity: '3 unidades', cost: 4200 },
      { item: 'Portas de Madeira com Batentes', quantity: '3 unidades', cost: 2700 },
      { item: 'Pontos Hidráulicos e Esgoto', quantity: '7 pontos', cost: 11000 },
      { item: 'Infraestrutura Elétrica e Iluminação LED', quantity: 'Geral', cost: 21175 },
    ],
  },
  agentDebates: [
    {
      id: 'msg-v1',
      agent: 'vision',
      message: 'Detecção de imagem concluída. Identifiquei 3 ambientes claros com divisórias integradas entre sala e cozinha.',
      timestamp: '16:53:25',
    },
    {
      id: 'msg-d1',
      agent: 'designer',
      message: 'Excelente! Sugeri piso laminado de madeira na área social para aquecer o ambiente e revestimento impermeável nas áreas úmidas.',
      timestamp: '16:53:30',
    },
    {
      id: 'msg-e1',
      agent: 'engineer',
      message: 'Estrutura viável. Verifiquei as cargas das divisórias e certifiquei que a iluminação natural da janela principal (1.6m) atende aos requisitos normativos de conforto.',
      timestamp: '16:53:38',
    },
  ],
};

export const mockRuralHouse: FloorPlanData = {
  rooms: [
    {
      id: 'rr1',
      name: 'Suíte Casal Conforto',
      x: 1.0,
      y: 1.0,
      width: 4.5,
      height: 4.0,
      color: '#fce7f3',
      floorMaterial: 'wood',
      wallColor: '#fff1f2',
    },
    {
      id: 'rr2',
      name: 'Banheiro Suíte',
      x: 5.5,
      y: 1.0,
      width: 2.0,
      height: 4.0,
      color: '#e0f2fe',
      floorMaterial: 'tile',
      wallColor: '#f0f9ff',
    },
    {
      id: 'rr3',
      name: 'Living Integrado com Varanda',
      x: 1.0,
      y: 5.0,
      width: 6.5,
      height: 5.0,
      color: '#ecfdf5',
      floorMaterial: 'concrete',
      wallColor: '#f0fdf4',
    },
    {
      id: 'rr4',
      name: 'Cozinha Gourmet Rústica',
      x: 7.5,
      y: 5.0,
      width: 3.5,
      height: 5.0,
      color: '#ffedd5',
      floorMaterial: 'tile',
      wallColor: '#fff7ed',
    },
  ],
  doors: [
    {
      id: 'dd1',
      roomId: 'rr1',
      wall: 'bottom',
      offset: 0.5,
      width: 0.9,
      isOpen: true,
    },
    {
      id: 'dd2',
      roomId: 'rr2',
      wall: 'left',
      offset: 1.5,
      width: 0.8,
      isOpen: false,
    },
    {
      id: 'dd3',
      roomId: 'rr3',
      wall: 'bottom',
      offset: 3.0,
      width: 1.5,
      isOpen: true,
    },
    {
      id: 'dd4',
      roomId: 'rr4',
      wall: 'left',
      offset: 2.0,
      width: 0.9,
      isOpen: true,
    },
  ],
  windows: [
    {
      id: 'ww1',
      roomId: 'rr1',
      wall: 'top',
      offset: 1.5,
      width: 1.8,
    },
    {
      id: 'ww2',
      roomId: 'rr2',
      wall: 'right',
      offset: 1.5,
      width: 0.8,
    },
    {
      id: 'ww3',
      roomId: 'rr3',
      wall: 'left',
      offset: 1.5,
      width: 2.4,
    },
    {
      id: 'ww4',
      roomId: 'rr4',
      wall: 'right',
      offset: 1.5,
      width: 1.5,
    },
  ],
  furniture: [
    {
      id: 'ff1',
      name: 'Cama King-Size',
      type: 'bed',
      roomId: 'rr1',
      x: 1.0,
      y: 0.5,
      width: 2.0,
      height: 2.2,
      rotation: 0,
    },
    {
      id: 'ff2',
      name: 'Guarda-roupa Moderno',
      type: 'cabinet',
      roomId: 'rr1',
      x: 0.5,
      y: 3.0,
      width: 2.5,
      height: 0.6,
      rotation: 90,
    },
    {
      id: 'ff3',
      name: 'Poltrona de Leitura',
      type: 'chair',
      roomId: 'rr1',
      x: 3.5,
      y: 2.8,
      width: 0.8,
      height: 0.8,
      rotation: 45,
    },
    {
      id: 'ff4',
      name: 'Sofá de Canto Grande',
      type: 'couch',
      roomId: 'rr3',
      x: 1.0,
      y: 0.5,
      width: 3.0,
      height: 1.8,
      rotation: 0,
    },
    {
      id: 'ff5',
      name: 'Mesa de Centro Rústica',
      type: 'table',
      roomId: 'rr3',
      x: 1.5,
      y: 2.5,
      width: 1.2,
      height: 0.8,
      rotation: 0,
    },
    {
      id: 'ff6',
      name: 'Painel Home e TV 65"',
      type: 'tv',
      roomId: 'rr3',
      x: 5.0,
      y: 0.5,
      width: 1.5,
      height: 0.4,
      rotation: 180,
    },
    {
      id: 'ff7',
      name: 'Mesa Gourmet Jantar',
      type: 'table',
      roomId: 'rr4',
      x: 0.5,
      y: 1.0,
      width: 2.2,
      height: 1.0,
      rotation: 90,
    },
    {
      id: 'ff8',
      name: 'Cadeiras de Jantar Especial',
      type: 'chair',
      roomId: 'rr4',
      x: 0.6,
      y: 3.2,
      width: 0.5,
      height: 0.5,
      rotation: 180,
    },
    {
      id: 'ff9',
      name: 'Fogão a Lenha Moderna',
      type: 'stove',
      roomId: 'rr4',
      x: 2.5,
      y: 0.5,
      width: 0.8,
      height: 0.8,
      rotation: 0,
    },
  ],
  estimatedCost: {
    structural: 112000,
    flooring: 28400,
    installations: 34000,
    total: 174400,
    materialsBreakdown: [
      { item: 'Fundações e Estrutura Cimento Queimado', quantity: '72 m²', cost: 58000 },
      { item: 'Alvenaria de Tijolos Ecológicos', quantity: '180 m²', cost: 42000 },
      { item: 'Assoalho de Madeira Maciça Tradicional', quantity: '18 m²', cost: 9500 },
      { item: 'Piso de Cimento Queimado Auto-nivelante', quantity: '32.5 m²', cost: 5200 },
      { item: 'Esquadrias Pivotantes e Grandes Painéis de Vidro', quantity: 'Geral', cost: 18500 },
      { item: 'Metais e Louças Sanitárias de Luxo', quantity: 'Banheiro', cost: 14000 },
      { item: 'Pontos Elétricos e Iluminação Decorativa Rustica', quantity: 'Geral', cost: 12200 },
      { item: 'Mão de Obra Especializada de Construção', quantity: 'Estimativa', cost: 15000 },
    ],
  },
  agentDebates: [
    {
      id: 'msg-v2',
      agent: 'vision',
      message: 'Planta de casa de campo identificada. Reconheci forte integração com áreas externas devido à grande porta de correr (1.5m) no Living.',
      timestamp: '16:00:00',
    },
    {
      id: 'msg-d2',
      agent: 'designer',
      message: 'Propus piso de cimento queimado na área social integrada e madeira maciça no quarto principal para elevar o aconchego rústico-elegante.',
      timestamp: '16:01:15',
    },
    {
      id: 'msg-e2',
      agent: 'engineer',
      message: 'O vão livre de 6.5 metros no Living exige uma viga de reforço estrutural. Já adicionei essa consideração ao orçamento estimado.',
      timestamp: '16:02:40',
    },
  ],
};
